# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@1.2
  codecov: codecov/codecov@3.2.0

jobs:
  build-core:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install .[tests,pytorch,keras]
            pytest --cov=latte --cov-report=xml
      - codecov/upload:
          file: coverage.xml

workflows:
  test:
    jobs:
      - build-core
      
