# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@1.2
  codecov: codecov/codecov@3.2.0

jobs:
  build36:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install .[tests,pytorch,keras]
            pytest --cov=latte --cov-report=xml

  build37:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install .[tests,pytorch,keras]
            pytest --cov=latte --cov-report=xml
  
  build38:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install .[tests,pytorch,keras]
            pytest --cov=latte --cov-report=xml
      - codecov/upload:
          file: coverage.xml

  build39:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install .[tests,pytorch,keras]
            pytest --cov=latte --cov-report=xml
      - codecov/upload:
          file: coverage.xml
  
  publish_testpypi:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Publish to TestPyPI
          command: |
            pip install --upgrade pip
            pip install twine build
            python -m build --sdist --wheel
            twine check dist/*
            twine upload --repository testpypi dist/*

workflows:
  test:
    jobs:
      - build36
      - build37
      - build38
      - build39
      - publish_testpypi:
          requires:
              - build36
              - build37
              - build38
              - build39
          filters:
            branches:
              only:
                - main
            tags:
              only: 
                - /^v[0-9]+(\.[0-9]+)*$/


      
