# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@1.2
  codecov: codecov/codecov@3.2.0

jobs:
  build37:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: deps37-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv37
            . venv37/bin/activate
            pip install --upgrade pip
            pip install .[tests,pytorch,keras]
      - run:
          name: Run tests
          command: |
            . venv37/bin/activate
            pytest -n 2 tests/ --cov=latte --cov-report=xml
      - save_cache:
          key: deps37-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv37"
      - codecov/upload:
          file: coverage.xml
  
  build38:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: deps38-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv38
            . venv38/bin/activate
            pip install --upgrade pip
            pip install .[tests,pytorch,keras]
      - run:
          name: Run tests
          command: |
            . venv38/bin/activate
            pytest -n 2 tests/ --cov=latte --cov-report=xml
      - save_cache:
          key: deps38-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv38"
      - codecov/upload:
          file: coverage.xml

  build38-torch-only:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: deps38torch-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv38torch
            . venv38torch/bin/activate
            pip install --upgrade pip
            pip install .[tests,pytorch]
      - run:
          name: Run tests
          command: |
            . venv38torch/bin/activate
            pytest -n 2 tests/metrics/ --cov=latte.metrics --cov-report=xml
      - save_cache:
          key: deps38torch-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv38torch"
      - codecov/upload:
          file: coverage.xml

  build38-tf-only:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: deps38tf-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv38tf
            . venv38tf/bin/activate
            pip install --upgrade pip
            pip install .[tests,keras]
      - run:
          name: Run tests
          command: |
            . venv38tf/bin/activate
            pytest -n 2 tests/metrics/ --cov=latte.metrics --cov-report=xml
      - save_cache:
          key: deps38tf-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv38tf"
      - codecov/upload:
          file: coverage.xml

  build38-core-only:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: deps38core-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv38core
            . venv38core/bin/activate
            pip install --upgrade pip
            pip install .[tests]
      - run:
          name: Run tests
          command: |
            . venv38core/bin/activate
            pytest -n 2 tests/metrics/ --cov=latte.metrics --cov-report=xml
      - save_cache:
          key: deps38core-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv38core"
      - codecov/upload:
          file: coverage.xml
            
  build39:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - restore_cache:
          key: deps39-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv39
            . venv39/bin/activate
            pip install --upgrade pip
            pip install .[tests,pytorch,keras]
      - run:
          name: Run tests
          command: |
            . venv39/bin/activate
            pytest -n 2 tests/ --cov=latte --cov-report=xml
      - save_cache:
          key: deps39-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv39"
      - codecov/upload:
          file: coverage.xml
  
  publish_testpypi:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: init .pypirc
          command: |
            echo -e "[testpypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $TESTPYPI_API" >> ~/.pypirc
      - run:
          name: Publish to TestPyPI
          command: |
            pip install --upgrade pip
            pip install twine build
            python -m build --sdist --wheel
            twine check dist/*
            twine upload --skip-existing --repository testpypi dist/*

  publish_pypi:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPI_API" >> ~/.pypirc
      - run:
          name: Publish to TestPyPI
          command: |
            pip install --upgrade pip
            pip install twine build
            python -m build --sdist --wheel
            twine check dist/*
            twine upload --repository pypi dist/*

workflows:
  build-test-publish:
    jobs:
      - build37
      - build38
      - build38-torch-only
      - build38-tf-only
      - build38-core-only
      - build39
      - publish_testpypi:
          requires:
              - build37
              - build38
              - build38-torch-only
              - build38-tf-only
              - build38-core-only
              - build39
          filters:
            branches:
              only: 
                - /^release.*/
            tags:
              only: 
                - /^v[0-9]+(\.[0-9]+).*/
      - publish_pypi:
          requires:
              - build37
              - build38              
              - build38-torch-only
              - build38-tf-only
              - build38-core-only
              - build39
              - publish_testpypi
          filters:
            branches:
              only:
                - /^release.*/
            tags:
              only: 
                - /^v[0-9]+(\.[0-9]+).*/


      
